### PR TITLE
README typo fix : space missing

### PR DESCRIPTION
**Pull request by staranjeet**

### CODE REVIEW

**Comment by metachris** [comment]
thanks :+1:

**Comment by staranjeet** [comment]
I ran a PEP8 check on this project and it showed many warnings. I was thinking of fixing those and submitting a PR for it. What say?
@metachris

**Comment by metachris** [comment]
I would be interested in taking a look!

**Comment by staranjeet** [comment]
Ok I will submit a PR for it. You can have a look then.

**Pull request merged**
